export const environment = {
  production: false,
  PORT: 0,

  SQL_PORT: 0,

  SQL_USERNAME: '',
  SQL_PASSWORD: '',
  SQL_SERVER: '',
  SQL_DATABASE: '',

  SENTRY_DSN: '',
  SENTRY_RELEASE: '',

  STRIPE_PUBLISHABLE_KEY: '',
  STRIPE_SECRET_KEY: '',
  STRIPE_WEBHOOK_SECRET: '',

  JWT_TOKEN_SECRET: '',

  AZURE_STORAGE_ACCESS_KEY: '',
  AZURE_STORAGE_CONNECTION_STRING: '',
  AZURE_STORAGE_ACCOUNT_NAME: '',

  ENV: '',
};
